### ISSUE TITLE
Tehran data should list 10 interchange stations

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#13]
Tehran currently has 9-11 interchange stations operational: https://en.wikipedia.org/wiki/Tehran_Metro#Interchange_stations
Please update your reference data at https://docs.google.com/spreadsheets/d/1-UHDzfBwHdeyFxgC5cE_MaNQotF3-Y0r1nW9IwpIEj8/edit#gid=2085714915 to include this figure.

**Comment by Zverik** [comment]
Hi, thanks for the update. I filled in the number for interchange stations, it's 11 now: I guess partially opened interchanges can count. I also enabled commenting on the spreadsheet, so please do that when the numbers change.
