### ISSUE TITLE
Tehran metro line 8 not included

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#20]
Tehran metro line 8 (route=subway) doesn't seem to be picked up properly: https://www.openstreetmap.org/relation/6151834
All stations along the way keep getting flagged as unused.

Does the whole route with all its way segments and nodes need to be completely within the bounding box?
I can't find any other reason - particularly tagging - which would prevent it.

**Comment by claudiush** [comment]
On a related note: It might be helpful if the output would include a list of detected routes for subways and light_rail/monorail with their name and not just the amount. This would help troubleshooting tremendously.

**Comment by Zverik** [comment]
Hi, I've added subway_entrances to stop_area relations in Iran (I have a handy tool for that), and made a yaml file with lines and stations: https://pastebin.com/A1xEhwhb

You can do that yourself: clone this repository, download a geofabrik extract for Iran and download osmctools binaries (osmconvert, osmfilter, osmupdate). Then convert pbf to o5m and run `scripts/process_subways.sh` with iran.o5m and "Iran" as parameters. You'll get an html validation page. If you specify "Tehran" for the second parameter, you'll get "Tehran.yaml" file with contents similar to the one I gave you.

**Comment by Zverik** [comment]
The route you show has only 3 stops in it — maybe you should add other stops as well.

**Comment by Zverik** [comment]
Okay, found the reason: the network wasn't added into "Networks" column in the Google Spreadsheet. Added that, now the line is counted. These are all the errors and warnings for Tehran now:

* An under construction stop in route (node 3815456757, "شهدای هفت تیر")
* Found 119 stations in routes, expected 106
* light_rail station "شهر آفتاب" in subway route (relation 6151834, "خط 8")
* light_rail station "فرودگاه امام خمینی" in subway route (relation 6151834, "خط 8") 

I've updated the pastebin document, so you can see which stations are counted.

**Comment by claudiush** [comment]
Thanks for looking into and fixing it. Weird that the network tag suddenly plays a role.

The airport metro line 8 indeed only has three stations as it is an express line from the airport to the southern connection of line 1.

**Comment by Zverik** [comment]
There is a fourth column in the spreadsheet. When its value is not empty, the processor skips any relations that don't have a network/operator tag with one of the values in that cell. That is useful when a city has multiple networks, e.g. U-Bahn and S-Bahn.
