### ISSUE TITLE
Caching for mapsme export

### ISSUE THREAD

**Issue by Zverik** [mapsme/subways#24]
Every good city should be cached. When loading from a cache (in case a network turned bad), all osm ids should be checked and entities with obsolete ids should be removed. Only if all stations remain and have at least one entrance and exit, the cached network should be used.

**Comment by alexey-zakharenkov** [comment]
Ilya,
can we close the issue? Current implementation of caching differs from your vision in that it doesn't consider change of entrances at all, because anyway mapsme export generates fake entrances in case of absence of osm entrances.

**Comment by Zverik** [comment]
Well, if you've got caching working, then yes, this can be closed.
