### ISSUE TITLE
Track direction test should honour direction relation member

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#30]
Subway validator warns about possible wrong track direction for relation 5623319. But the tracks are "backward" relation member so going the other way direction the stop order is correct.

**Comment by Zverik** [comment]
As of PT schema version 2, forward/backward roles are obsolete. This script automatically rotates ways so they form a contigous line. But you are right, this might cause an unsolvable warning when two routes share the same long way. Fixed that in d46f083 — but it might not work when a route has two or more ways.
