### ISSUE TITLE
Running validation on a single city

### ISSUE THREAD

**Issue by asdzxcasd** [mapsme/subways#33]
I want to try, how validation works for a single city, e.g. London. I have tried running
`./process_subways.py -c London`
but it doesn't work and returns HTTP Error 429: Too Many Requests

However that script uses OverpassAPI, so I guess that I need to download .osm myself. Obviously nobody wants to download entire `planet.osm` (or `planet.pbf`) if just a single city is needed. Readme mentions `osmconvert` tool, but I didn't find anything helpful on [https://wiki.openstreetmap.org/wiki/Osmconvert](url) to download data for a city without downloading the planet. It would be great if readme explained that step in more details, maybe providing links that explain data importing in-depth.

**Comment by Zverik** [comment]
Just download Greater London from [Geofabrik](http://download.geofabrik.de/europe/great-britain/england.html) and convert it to o5m: `osmconvert greater-london.osm.pbf -o=longon.o5m`.

**Comment by Zverik** [comment]
Also, you should use `CITY=London ./process_subways`. I assume it is displayed when you run the script without parameters.

**Comment by asdzxcasd** [comment]
After a few attempts of running the script I think that the reason of why the default option is to download the whole planet is that some relations in OSM stretch beyond city bounds, resulting in errors like this one:

`Stop or platform node 1555998673 in relation 102768 is not in the dataset for London`

**Comment by Zverik** [comment]
I have added a `build_city.sh` script, now processing a city should be easier. Also, you might try just with an England extract. I think Greater London worked for me, but I'm not that sure now.
