### ISSUE TITLE
Route relations consisting of a single way report warning

### ISSUE THREAD

**Issue by disc12** [mapsme/subways#35]
http://osmz.ru/subways/mexico.html

For Monterrey, reports "Tracks seem to go in the opposite direction to stops (relation 7890222, "Línea 1") "

Not possible for track to be in the opposite direction because the route consists of a single way

**Comment by Zverik** [comment]
Such warnings are solved by adding a `backward` role to the way. I'm not sure it is correct, but making things explicit is better, to my taste.
