### ISSUE TITLE
Improve information and reduce duplication of entries for error about multiple stations in stop_area

### ISSUE THREAD

**Issue by disc12** [mapsme/subways#37]
http://osmz.ru/subways/china.html
e.g.
"Stop area has multiple stations (relation 2207110, "郭公庄")"

This entry with identical wording shows up six times.  It would be more helpful to list the relation, with a list of the nodes for different stations in the stop_area.

**Comment by Zverik** [comment]
This error is displayed once for each station in a stop_area, because of how stations are processed. I agree that doesn't give the complete context needed for fixing the relation. But in most cases, like the cited one, it is obvious. If it isn't, send me an example and I'll see what I can do.
