### ISSUE TITLE
Subway Line Route Relations being ignored 

### ISSUE THREAD

**Issue by disc12** [mapsme/subways#39]
http://osmz.ru/subways/brazil.html

For Rio de Janeiro 
6 unused stations: n4317159358, n4317159359, n4317159360, n4317159361, n5302148205, n5362542035

Yet these stations are members of two Linha 4 relations, one in each direction

**Comment by Zverik** [comment]
Look, when you click on a pale "Y" link near to the city name, you'll get a file with a list of all stations, transfers and routes. You'll notice the Linha 4 route is missing. In [the spreadsheet](https://docs.google.com/spreadsheets/d/1-UHDzfBwHdeyFxgC5cE_MaNQotF3-Y0r1nW9IwpIEj8/edit#gid=2085714915) there is a network labelled for Rio Metro: "Metrô Rio". Linha 4 relations did not have a `network` tag with that value. The fallback is `operator` tag, but it has "MetrôRio" without a space. So, to process the route and to use stations in it, it needs to have the proper network tag. I've just added it.
