### ISSUE TITLE
Dalian Metro Line 12 not recognized

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#40]
Any idea why Dalian Metro Line 12 is not recognized in http://osmz.ru/s ubways/dalian.yaml ?
The route master relation is https://www.openstreetmap.org/relation/7957874

It contains the same network=Dalian Metro tag as the other three lines that are recognized correctly.

**Comment by Zverik** [comment]
I think that's because the bounding box for the city did not include the peninsula. I've updated it, we'll see how it goes.
