### ISSUE TITLE
Subway Validator should factor in number of stops on routes more than number of stations

### ISSUE THREAD

**Issue by disc12** [mapsme/subways#41]
In multiple cases, e.g. Mexico, Los Angeles, Cleveland, multiple Asian cities, station counts don't match station counts for several reasons:

- If multiple subways or multiple light rail lines stop at the same station location, they may all be associated with a single station node (or associated stop node) or they may be associated with different station nodes with the same station name.

- If a light rail line and a subway line meet, each requires a separate station node

Counting the number of total stops on all of the applicable routes would be more effective

**Comment by Zverik** [comment]
Good idea, disc12. This might help with the single-vs-multiple stations per transfer issue. I will think about this.
