### ISSUE TITLE
Subway Lines in Kaohsiung, Taiwan are not being detected

### ISSUE THREAD

**Issue by disc12** [mapsme/subways#43]
Orange and Red subway routes were built months ago, but are not being picked up by subway validator.  See the following node, which has route relations where the two routes intersect.
https://www.openstreetmap.org/node/4580663526

Also, the Circular light rail line is present as a tram route.  It looks more like a tram route than light rail as per wikipedia: 
https://en.wikipedia.org/wiki/Circular_light_rail

See following node with the route relation for the circular line, as a tram route
https://www.openstreetmap.org/node/4576225719

**Comment by Zverik** [comment]
There was an incorrect network name set in the spreadsheet. Changed it to the one used in `operator` tag.
