### ISSUE TITLE
Multiple Subway lines in Hong Kong, China not being detected

### ISSUE THREAD

**Issue by ghost** [mapsme/subways#44]
Subway validator is detecting MTR Island Line and South Island Line
https://www.openstreetmap.org/relation/4432666
https://www.openstreetmap.org/relation/6827211

But not other lines, e.g. Tsuen Wan, Tung Chung, Airport Express, Kwun Tong, West Rail Line, East Rail Line
https://www.openstreetmap.org/relation/269669
https://www.openstreetmap.org/relation/5317704
https://www.openstreetmap.org/relation/5317239
https://www.openstreetmap.org/relation/6452935
https://www.openstreetmap.org/relation/6582966
https://www.openstreetmap.org/relation/4248590

**Comment by Zverik** [comment]
Hmm, none of these lines should've been detected, since the network differs from these listed on the spreadsheet. I've updated it, let's see how it goes.

**Comment by Zverik** [comment]
Nope, that wasn't the reason. Checking it again.

**Comment by alexey-zakharenkov** [comment]
All the forementioned lines have been checked to be detected.
