### ISSUE TITLE
Interchange station in Kuala Lumpur

### ISSUE THREAD

**Issue by MASangys** [mapsme/subways#48]
The Rapid KL have a lot of interchange station which is formerly seperated and the platform are not in a same level.  

This is the list, I will update later and I hope somebody to update this table too thank youhttp://osmz.ru/subways/malaysia.html.

KL Sentral (Transport Hub)
Bandar Tasik Selatan
Kajang
Sungai Buloh
Subang Jaya
Titiwangsa
Masjid Jamek
Plaza Rakyat plus Merdeka
Hang Tuah
Maluri
Bukit Bintang

And also can anybody put the KL Monorail route into that Rapid Transit table? In Malaysia, monorail is a type of public transport that almost like subway but only one track.

**Comment by MASangys** [comment]
And also Pasar Seni 

Noted that Kajang,Sungai Buloh and Subang Jaya interchange with commuter service. (as well as Bandar Tasik Selatan) Bandar Tasik Selatan interchange with Airport railway. Titiwangsa, Hang Tuah and Bukit Bintang interchange with monorail.

According to this http://osmz.ru/subways/kuala_lumpur.yaml only Maluri and Masjid Jamek not on the transfer station list. If this only include Rapid Transit with Rapid Transit interchange (not include Monorail), I think this http://osmz.ru/subways/index.html 5 interchange only. (8 include Monorail, 9 include Airport railway and 12 include commuter service or suburban railway as of 2018)

**Comment by MASangys** [comment]
Almost done, Just need some people to help update this list
http://osmz.ru/subways/index.html
AG SP 29+7=36
SBK=31
KJ=37
Total=104
But that table display as 110, how it could be?

**Comment by Zverik** [comment]
I've updated the number using data from Wikipedia: it is now 31 (SBK) + 18 (AG) + 29 (SP) + 37 (KJ)  =115. I have also set the expected number of interchanges to 5, like you suggested. Thank you for tidying up the system!

**Comment by MASangys** [comment]
Oh, Thank you. But I have a question, why KL Monorail cannot be include into the subway system. Chongqing's Line 2 and Line 3 are monorails and already included in the list. Kuala Lumpur’s Line 8 (KL Monorail) is also a monorail and should also be included inside.

In Malaysia, the monorail is also a type of rail transit, and also can transfer with the metro (such as Titiwangsa station, future integrate with MRT)

**Comment by Zverik** [comment]
No problem, added the monorail line with 11 stations. Will be shown after the next update.

**Comment by MASangys** [comment]
OK, Thank You for your update.

**Comment by MASangys** [comment]
Interchange should increase to 8 now.

**Comment by MASangys** [comment]
And also one thing, why the KL Monorail alrady have relation 
https://www.openstreetmap.org/relation/2546881
but still cannot detect by Subway Validation, can you correct it?

**Comment by Zverik** [comment]
You can: please change `line=monorail` to `route=monorail`.

**Comment by MASangys** [comment]
OK, and the number of interchange is 9, I forgot tgat Dang Wangi and Bukit Nanas can be interchange.

**Comment by MASangys** [comment]
Hello Zverik. May I ask you a question about the future MRT line edit in Kuala Lumpur. A user now added https://en.wikipedia.org/wiki/Sungai_Buloh–Serdang–Putrajaya_MRT_line which is scheduled to open in 2022 and the new line causes subway validator error. Maybe you should add a tag for the proposed or construction subway. That line already have https://www.openstreetmap.org/relation/8298259 relation and currently there is no tag for the future line.  plus there have many new user doesn't know the subway validate causes Kuala Lumpur's metro system become messy now.  May I know your opinion about this? Thank you.

**Comment by MASangys** [comment]
and this 
Stop "Phileo Damansara" (pos) is nowhere near the tracks (relation 8000325, "Laluan MRT Jajaran Sungai Buloh – Kajang (Kajang --> Sungai Buloh)")

And this also
Hole in route rails near node n3857582320 (relation 8000325, "Laluan MRT Jajaran Sungai Buloh – Kajang (Kajang --> Sungai Buloh)")
What does it mean?

**Comment by MASangys** [comment]
http://osmz.ru/subways/malaysia.html

**Comment by claudiush** [comment]
If the MRT Laluan Sungai Buloh-Serdang-Putrajaya line is not operational yet, than the tagging https://www.openstreetmap.org/relation/8298259 is plain wrong as that would be the tagging for an already opened one.
You would therefor change **route=subway** for this relation to **construction:route=subway**

**Comment by claudiush** [comment]
Regarding the other two errors:

- **"Stop "xxxx" (pos) is nowhere near the tracks":** all stop route relation members need to be nodes on the railway ways that form the tracks of the route. Usually this error is caused by the station having two stop positions for each direction and the wrong being added to the route
- **"Hole in route rails near":** All railway way members that form the track of a route need to be sorted from start to finish with no holes in the track. If you are using JOSM to edit simply use the "sort relation members" button on the left of the route's relation editor. JOSM relation editor will also highlight with red dots if subsequent ways are not connected:
![image](https://user-images.githubusercontent.com/428616/40660929-b5f0bffe-6352-11e8-8902-52b77e33d89b.png)

**Comment by MASangys** [comment]
Sorry but my computer cannot use and I only can edit via the mobile page. I haven't use JOSM.and unfortunately my computer cannot use JOSM too although I tried. Never mind, if you could help this I will be grateful. 

BTW, Angle between stops around "Gombak" is too narrow, 6 degrees (relation 8000438, "Kelana Jaya Line (Putra Heights --> Gombak)") what does it means

**Comment by MASangys** [comment]
Oh I think you do a wrong edit. 
Laluan MRT Jajaran Sungai Buloh – Kajang=MRT SBK (Line 1), has been pperated since 2017
MRT Laluan Sungai Buloh-Serdang-Putrajaya=MRT SSP (Lime 2), still under construction now.

**Comment by claudiush** [comment]
Terribly sorry. That shouldn't have happened. I've fixed it now and also updated the colour tagging to green. I'm a bit confused by the SSP/SBK ref being used. According to Wikipedia their line reference numbers should be 9 ( https://en.wikipedia.org/wiki/Sungai_Buloh%E2%80%93Kajang_MRT_line ) and 12 ( https://en.wikipedia.org/wiki/Sungai_Buloh%E2%80%93Serdang%E2%80%93Putrajaya_MRT_line ). I guess SSP and SBK are the informal abbreviations then?

**Comment by MASangys** [comment]
Actually 9 and 12 only can seen from their official route map and you cant find it in the station.
https://www.myrapid.com.my/traveling-with-us/how-to-travel-with-us/rapid-kl/mrt
Maybe because they use color more. Normally I got the RGB code from https://en.wikipedia.org/wiki/Template:KLRT_color. SSP and SBK (https://www.mymrt.com.my/public/sg-buloh-kajang-sbk-line/) are real because they use 3 place name in a line. Not many foreigns know where is Serdang, Sungai Buloh and probably Putrajaya unless seethe maps.

**Comment by MASangys** [comment]
BTW, I think.the SSP line should sort too. Many of the construction station tagged as station only.

**Comment by MASangys** [comment]
http://osmz.ru/subways/malaysia.html
Now how can thsi happen.
An under construction stop in route (node 3857582234, "SBK05A Teknologi (Future)")
stop node 3857582234 is not connected to a station in route (relation 5690837, "Laluan MRT Jajaran Sungai Buloh – Kajang (Sungai Buloh --> Kajang)")

Noted that that statuon was an future station, as well as for Bukit Liars (https://www.openstreetmap.org/node/3857582083), so that means those future station cannot in the line relation?

**Comment by claudiush** [comment]
No. Future stations shouldn't be included in the route as they are not where the station stops.
I don't think there is currently a tagging scheme that supports planned or under construction route parts.
The closest really is to create a new relation with the track sections and stations that are under construction. Then tag this as construction:route=subway and add it to the route_master to create the connection
