### ISSUE TITLE
Unused station

### ISSUE THREAD

**Issue by sb12** [mapsme/subways#49]
What is meant by the "unused station" warning? For example in Germany every city gets a lot of these warnings. All the stations I checked were in a stop area relation and used by some route.

**Comment by claudiush** [comment]
Were they also used by a metro (subway or light_rail) route relation. 
Can you share one or more example links so we can have a look?

**Comment by sb12** [comment]
Example: https://www.openstreetmap.org/node/248345538 in Hamburg (one of the first ones listed at http://osmz.ru/subways/germany.html)
It seems to happen mainly in cities where there is more than one metro system.

**Comment by claudiush** [comment]
I think it's caused by Hamburg having two networks, one for U-Bahn and the other for S-Bahn.
So I think the U-Bahn network lists all S-Bahn stations as "unused" and vice versa.

**Comment by Zverik** [comment]
Yes, there can be stations from another network, like in german cities. Thanks Claudius for answering questions here :)
