### ISSUE TITLE
Are you going to add networks that are light rail only?

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#50]
There is "S-Bahn Mitteldeutschland" in the Leipzig-Halle region in Germany with 10 lines and 141 stations. Including a tunnel section under the city center: https://en.wikipedia.org/wiki/S-Bahn_Mitteldeutschland
None of the infrastructure is subway, but everything light rail. Are you intending to support these networks as well?
If yes: How would I request it to be added to the spreadsheet?

**Comment by Zverik** [comment]
Of course, any railway-based network that has stations would do, even trains. I would need a value for all the cells in a new row: city, bounding box, number of lines, stations and interchanges.

**Comment by claudiush** [comment]
Great. Two comments:
- **Name:** The system is an extension of the previous "Leipzig-Halle S-Bahn" and is now called "Middle German urban rapid railroad". And that name is also what it is referred to locally. If you want to preserve a city reference you could still call it ""Leipzig-Halle S-Bahn".
- **Bounding box:** This has actually grown pretty large now and the bounding box even encompasses the city of Dresden. Dresden has it's own separate S-Bahn network (VVO, 3 light rail lines, 48 stations) which is currently not yet covered by the subways processor

Here's the details you asked for:
name: S-Bahn Mitteldeutschland
bbox: 11.907233,50.698847,14.257053,51.869652
lines: 10 light rail lines
stations: 141
interchanges: 10
network: Mitteldeutscher Verkehrsverbund

**Comment by Zverik** [comment]
When a bounding box contains multiple networks (Leipzig S-Bahn and Dresden S-Bahn in this case), please use `network` tags on routes and route_masters to separate these. When it's not possible (like in Germany), use `network:metro=*`.

**Comment by Zverik** [comment]
The validator will finish in half an hour, you'll see the results here: http://osmz.ru/subways/germany.html

**Comment by claudiush** [comment]
Similar problem as with Nuremburg it seems:
There are various regional trains that are also operating in the same network. I've started adding network:metro=sbahn to the routes.
@Zverik Can you add this additional network restriction for both Dresden and Leipzig, please?

**Comment by Zverik** [comment]
Did that just now and started the validator. You will see the results in an hour.

**Comment by claudiush** [comment]
Thanks.

Seems there's a slight problem since Leipzig/Halle and Dresden S-Bahn networks are overlapping. I therefor currently see Dresden S-Bahn routes listed for Leipzig/Halle.

Can you make a logical AND a requirement for route networks, e.g. the following requirements:
- Leipzig/Halle: **network=Mitteldeutscher Verkehrsverbund** && **network:metro=s-bahn**
- Dresden: **network=VVO** && **network:metro=s-bahn**

**Comment by claudiush** [comment]
The Leipzig network has one line which is reaching very far East and ends northeast of Dresden. Also it reaches very far South which leads to the Leipzig bbox encompassing the Dresden network in large parts.

I've just re-tagged the Dresden routes to
Dresden: **network=VVO** && **network:metro=S-Bahn Dresden**

**Comment by claudiush** [comment]
And while we are at it here's another light rail network in **Magdeburg**:

name: S-Bahn Mittelelbe
bbox: 11.617733,51.997556,11.868564,53.00376
lines: 1 light rail line
stations: 28
interchanges: 0
network: Magdeburger Regionalverkehrsverbund
network:metro=s-bahn

This should be more straight forward without any overlapping neighbouring networks

**Comment by Zverik** [comment]
Added it, under name "Magdeburg S-Bahn". I know the name is not exactly correct, but it helps with identifying the central city for the route.
