### ISSUE TITLE
Invalid network diff warning 

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#53]
For Leipzig-Halle S-Bahn there are various invalid "different network" warnings. They are invalid as the network is only set in the route_master relations. Actually "DB Regio Südost" is only used as operator in the route childrens. Any idea why there seems to be a comparison taking place between child operator and parent master network tags?

Route has different network ("DB Regio Südost") from master "Mitteldeutscher Verkehrsverbund" (relation 7805410, "S-Bahn S 9: Halle (Saale) Hbf => Eilenburg")
Route has different network ("DB Regio Südost") from master "Mitteldeutscher Verkehrsverbund" (relation 3119885, "S-Bahn S 2: L-Stötteritz => Dessau")
Route has different network ("DB Regio Südost") from master "Mitteldeutscher Verkehrsverbund" (relation 2606967, "S-Bahn S 5: Halle (Saale) Hbf => Zwickau (Sachs) Hbf")
Route has different network ("DB Regio Südost") from master "Mitteldeutscher Verkehrsverbund" (relation 3119884, "S-Bahn S 2: Dessau => L-Stötteritz")
Route has different network ("DB Regio Südost") from master "Mitteldeutscher Verkehrsverbund" (relation 378138, "S-Bahn S 4: Hoyerswerda => Oschatz")

**Comment by Zverik** [comment]
The validator uses a value of `operator` tag if it doesn't find a `network`. In these cases, you would need to add one.

**Comment by claudiush** [comment]
Cascading the network tags down from route master to route relation indeed removes these warnings.
