### ISSUE TITLE
Wrong station count in overview, correct in YAML

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#54]
Both the Leipzig and Dresden S-Bahn networks show a weird station count bug on http://osmz.ru/subways/germany.html
E.g. for Dresden an error says "Found 62 stations in routes, expected 48"
for Leipzig "Found 211 stations in routes, expected 141"
But when I count the stations list in http://osmz.ru/subways/dresden_s-bahn.yaml and http://osmz.ru/subways/leipzig_s-bahn.yaml I get to 48 stations and 136 respectively.

Any idea where the higher station count is coming from?

**Comment by Zverik** [comment]
Stations are counted separately for each line. For Dresden S-Bahn at the moment, 47 stations are listed in the "stations" list, but when you take station lists for each of the routes, you get 32+16+11=59 stations. This way the count is not affected by interchange types, and can easily be verified using line information.

**Comment by claudiush** [comment]
Thanks for updating the station count. I will try to keep this in mind (although it seems I forget how the validator counts stations every 3 months :man_facepalming: )
