### ISSUE TITLE
entrances for stations outside of BBox

### ISSUE THREAD

**Issue by sb12** [mapsme/subways#55]
For the [Seoul Neotrans network](http://osmz.ru/subways/south-korea.html) there are currently 3 not-used entrance errors. They are connected to a [station](https://www.openstreetmap.org/node/355173443) which lies outside the BBox, while the [ent](https://www.openstreetmap.org/node/3401440050)[ran](https://www.openstreetmap.org/node/3408545515)[ces](https://www.openstreetmap.org/node/4670321856) are inside.
Can this be fixed on the software site or should just the BBox be adapted (which might lead to new similar errors)?

**Comment by Zverik** [comment]
Thanks for investigating the problem, sb12! I've modified the bbox, so the issue disappears.

**Comment by sb12** [comment]
It happened again for the same network, so maybe bbox needs to be modified again or is a more stable solution possible?
