### ISSUE TITLE
Allow railway=halt for stops in stop areas

### ISSUE THREAD

**Issue by claudiush** [mapsme/subways#56]
Stations for light rail infrastructure is often tagged using https://wiki.openstreetmap.org/wiki/Tag:railway%3Dhalt
The Subway validator only picks this up if the tag is used on the stop node. If railway=halt is a member in a stop area relation together with public_transport=stop_position and these stop position are used as route relation stops then validator complains "stop node #### is not connected to a station in route"

Same setup works if the station node is tagged as railway=station instead of railway=halt

Please allow railway=halt also as station nodes.

**Comment by alexey-zakharenkov** [comment]
@claudiush 
Is the issue still relevant? Does the halt https://www.openstreetmap.org/node/6607085791 correspond the described stop area arrangement?

**Comment by claudiush** [comment]
This seems to have been fixed for a while now as the validator is not complaining any longer about the setup you linked.
Good to close this ticket.
