### ISSUE TITLE
Dubai

### ISSUE THREAD

**Issue by bjohas** [mapsme/subways#57]
For Dubai, when I turn on the public transport overlay in maps.me, only the red and green lines show (the metro lines). Maybe that is automatic and cannot be changed. 

However, on Dubai public transport overview plans (i.e. paper posters in stations), the tram (orange) and monorail (thin black) is always shown alongside the two metro lines (red/green). 

So I suggest that in maps.me, when you turn on the transport overlay, those two lines are also shown, to provide a consistent experience for the traveller.

(The information is correct on OSM, so this is an issue with the way the lines are displayed when you switch the public transport overlay on, rather than an issue with OSM data.)

**Comment by claudiush** [comment]
I assume you are referring to the Palm Jumeirah Monorail (and not the other Airport People Mover monorail at the airport). I've updated the route list data document accordingly and this should be included in the next map update.

**Comment by bjohas** [comment]
That's correct 'Palm Jumeirah Monorai'. Many thanks!
