### ISSUE TITLE
Add more rapid transit routes in Metropolitan Tokyo [subway, light rail and commuter]

### ISSUE THREAD

**Issue by sguinetti** [mapsme/subways#61]
Hello. I was reviewing the [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1-UHDzfBwHdeyFxgC5cE_MaNQotF3-Y0r1nW9IwpIEj8/edit#gid=2085714915), and I want to add missing routes. There are more rapid transit routes for some areas in Tokyo. I have adapted with the [Openstreetmap wiki guide](https://wiki.openstreetmap.org/wiki/Metro_Mapping). They are popular and have good passenger demand for day.

**What is this list?**

I have categorized the lines according to route type. That will expedite the review of these relationships. It is linked with other issues, although in the end the idea remains the same.

Each item represents a separate line with its respective rail network. So all, they are new networks (they are different from Tokyo Metro and Toei subway).

Thank you. I hope that with this contribution it helps a lot to walk around Tokyo (and be ready at the Olympic Games of 2020).

Update: I added Toyo Rapid Line, it's characterized like a suburban route. I added intervals and [hours of attention](https://wiki.openstreetmap.org/wiki/User:DSMap/Horario_del_metro_de_Tokio) (wiki page in spanish-language) for better control of the rapid transit routes.

Update 2: Added commuter rail lines like Paris RER (they link to other cities around Metropolitan Tokyo). For example, Tokyu network goes to Yokohama city (and its subways).

**Comment by sguinetti** [comment]
Update. I added Toyo Rapid Line, it's characterized like a suburban route. I added intervals and [hours of attention](https://wiki.openstreetmap.org/wiki/User:DSMap/Horario_del_metro_de_Tokio) for better control of the rapid transit routes.

**Comment by sguinetti** [comment]
Subway:
- [Yurikamome](https://www.openstreetmap.org/relation/9221982) ([Wikipedia](https://en.wikipedia.org/wiki/Yurikamome)) Like Rinaki line, company that also makes competition, takes passengers through Tokyo Bay. But it differs for being light rail and it is a bit more expensive to get an entrance to use one of its trains. Ref: U.
- [Toden Arakawa Line](https://www.openstreetmap.org/relation/9254426) ([Wikipedia](https://en.wikipedia.org/wiki/Toden_Arakawa_Line), operated by Toei) Tram to take some locations north of Tokyo. It has functions similar to Light rail. Ref: SA
- [Toyo Rapid Line](https://www.openstreetmap.org/relation/5326658) ([Wikipedia](https://en.wikipedia.org/wiki/T%C5%8Dy%C5%8D_Rapid_Railway_Line), operated by 東葉高速鉄道) . Underground rapid line to Chiba. Ref: TR

**Comment by sguinetti** [comment]
**Commuter rail**
* Keisei. See [Wikipedia](https://en.wikipedia.org/wiki/Keisei_Electric_Railway).
* Tokyu. See [Wikipedia](https://en.wikipedia.org/wiki/Tokyu_Corporation).
* Keiyu. See [Wikipedia](https://en.wikipedia.org/wiki/Keikyu).

**Comment by alexey-zakharenkov** [comment]
**sguinetti**,

thanks for your endeavour, but there are a too many [commuter train networks](https://en.wikipedia.org/wiki/List_of_suburban_and_commuter_rail_systems) and other [rapid transit systems](https://en.wikipedia.org/wiki/Lists_of_rapid_transit_systems) around the world. The goal of the "Rapid" google sheet is to encompass primarily metro systems. Other types and lines are included if they are drawn on official scheme of a city metro.

This doesn't prevent from validating other routes. You may create similar google doc sheet with your transport systems and validate with it (or, if it's difficult/impossible, ask me run the validator with it).

**Comment by sguinetti** [comment]
> **sguinetti**,
> 
> thanks for your endeavour, but there are a too many [commuter train networks](https://en.wikipedia.org/wiki/List_of_suburban_and_commuter_rail_systems) and other [rapid transit systems](https://en.wikipedia.org/wiki/Lists_of_rapid_transit_systems) around the world. The goal of the "Rapid" google sheet is to encompass primarily metro systems. Other types and lines are included if they are drawn on official scheme of a city metro.
> 
> This doesn't prevent from validating other routes. You may create similar google doc sheet with your transport systems and validate with it (or, if it's difficult/impossible, ask me run the validator with it).

I'm sorry. I did not expect that goal. I admit that I've added the routes to the main city to make it easy for other users. I thank you in the creation of the Google sheet. However, you must complete this section first and later you will suggest me in the validation of other and minor routes.

On the official website of the [Tokyo Metropolitan](https://www.kotsu.metro.tokyo.jp/eng/services/pdf/sub_map_eng.pdf) I found all possible routes. So I will remove the ones that are not necessary (so keep simple the task) and I will focus on the commuter and subway lines: If you appreciate that map you will see certain blue thickened lines leading to the airport. The "Toden Arakawa Line" I keep it because it is on the map with Nippori-Toneri.
