### ISSUE TITLE
Invalid validation yaml file

### ISSUE THREAD

**Issue by yatsyk** [mapsme/subways#68]
`python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < ~/Downloads/prague.yaml`

generates error on line

`    name: Metro linka A: Nemocnice Motol → Depo Hostivař`

Consider to use yaml library for yaml file generation instead of concatenating strings manually.

**Comment by Zverik** [comment]
The idea was to not use any external libraries, and with yaml, installation of it can be harder than usual.

**Comment by yatsyk** [comment]
Make sense. I think adding double quotes around name should fix the problem.

**Comment by alexey-zakharenkov** [comment]
Fixed in PR #87
