### ISSUE TITLE
Incorrectly added pt=stop_position in a route does not trigger any alert

### ISSUE THREAD

**Issue by alexey-zakharenkov** [mapsme/subways#85]
Let's consider the following scenario. A public_transport=stop_position was correctly bound to a station via stop_area relation and added into a route in correct position. Imagine somebody recreates the stop_position and makes the following mistakes:
1) they do not add new stop_position into the stop_area relation;
2) they add the stop_position to the end of the route relation, breaking stops order;
3) they do not set 'stop' role to the stop_position in a route relation.

**Expected validator behavior**: "{role} node {id} is not connected to a station in route" or some other error appears.

**Observed behavior**: no error is produced, only station count decreases by one. In case when one of two route directions is mapped correctly, even station count doesn't change.

An error would be generated if the stop_position were added to the stop_area, or it had the stop/platform role.

Should we really ignore route relation member with role other than 'stop/platform', even if it IS a stop/platform?

**Comment by Zverik** [comment]
More correct way would be to assume "stop" role for stop positions (and "platform" for platforms) — I thought that's what it does.
