### ISSUE TITLE
Add commuter rail networks in Greece (Προαστιακός)

### ISSUE THREAD

**Issue by Robot8A** [mapsme/subways#92]
Προαστιακός https://en.wikipedia.org/wiki/Proastiakos

Athens: https://www.openstreetmap.org/relation/8467449
4 lines, 45 stations https://en.wikipedia.org/wiki/Proastiakos_Athens

Thessaloniki: Not yet mapped in OSM
2 lines, 25 stations https://en.wikipedia.org/wiki/Proastiakos_Thessaloniki

**Comment by alexey-zakharenkov** [comment]
Now a new validation with commuter train services is deployed at Maps.Me server: http://osm-subway.maps.me/commuter. All forementioned networks are already included.

You may leave comments with your wishes in 'Commuter' sheet of google spreadsheet document with transport networks. The link to the google doc is available in README of this repo.
